# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /:year/:month/:title/
relative_permalinks: false

# Setup
title:            get lost here
tagline:          'bloggy bloggy blog'
description:      'not all who wander are lost. Made by <a href="https://twitter.com/perftestgoddess" target="_blank">@perftestgoddess</a>.'
url:              http://violetaria.github.io
baseurl:          /

author:
  name:           'Terri Chu'
  url:            https://twitter.com/perftestgoddess
  email:          terri.chu@outlook.com
  
gems:             [jekyll-paginate]

paginate:         1

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

