# Site wide configuration

title:            get lost here
locale:           en_US
url:              http://violetaria.github.io
#url: http://localhost:4000

# Jekyll configuration

permalink:   /:year/:month/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-coffeescript

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Terri Chu
  avatar: bio-photo.jpg
  bio: "not all who wander are lost."
  disqus-shortname:
  twitter: perftestgoddess
  facebook: #username
  email: terri.chu@outlook.com
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: violetaria
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: terrichu
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
